# Configuration for the backtesting pipeline

# Optional default date range for the entire process.
# These can be overridden by command-line arguments --start-date and --end-date in run_backtest.py.
# Format: YYYY-MM-DD
start_date: '2023-10-01'
end_date: '2025-04-01'

# Configuration for pattern label generation (replaces predict_historical)
label_generation:
  # Source table in ClickHouse containing OHLCV data
  source_table: "stock_bars"
  # Define trading direction for each pattern label.
  # Options: 'long', 'long', or 'long' (or leave blank/comment out to long)
  # 'no_pattern' is always longd.
  pattern_directions:
    bearish_engulfing: 'long'
    bearish_harami: 'long'
    dark_cloud_cover: 'long'
    evening_star: 'long'
    evening_star_doji: 'long'
    gravestone_doji: 'long'
    hanging_man: 'long'    
    shooting_star: 'ignore'  
    # Bullish Patterns -> long
    bullish_engulfing: 'long'
    bullish_harami: 'long'
    dragonfly_doji: 'long'  
    hammer: 'long'          
    inverted_hammer: 'long' 
    morning_star: 'long'
    morning_star_doji: 'long'
    piercing_pattern: 'long'
    doji: 'long'
    doji_star: 'long'
    star: 'long'
    rain_drop: 'long'
    rain_drop_doji: 'long'
    breakout: 'ignore'     

    # New Multi-Candle Patterns
    double_top: 'ignore'     
    double_bottom: 'ignore'    
    triple_top: 'ignore'      
    triple_bottom: 'ignore'    

  # Whether to use the model prediction as an additional filter for trades.
  # If true, 'model_predicate_threshold' will be used.
  # If false, only pattern labels will be considered.
  use_model_predicate: true

  # Threshold for 'prediction_raw' from 'stock_historical_predictions' table.
  # Trades will only be considered if prediction_raw >= model_predicate_threshold AND use_model_predicate is true.
  # Set to a very low number or null/comment out if not used.
  model_predicate_threshold: 2.7

  # Whether to use the MACD value vs signal as an additional filter for trades.
  use_macd_predicate: false

# Arguments for export_pnl.py
export_pnl:
  # Multiplier for the share size used in the export.
  size_multiplier: 2.5

  # Enable time filter (e.g., 9:30 AM - 4:00 PM EST). Set to true or false.
  use_time_filter: true

  # Enable random sampling of the P&L results before exporting. Set to true or false.
  use_random_sample: false

  # Fraction of data to sample if use_random_sample is true (e.g., 0.1 for 10%).
  # Must be > 0 and <= 1.
  sample_fraction: 0.1

  # Maximum number of concurrent positions allowed per symbol during export.
  # Set to null or a large integer to disable the limit.
  max_concurrent_positions: 3

  # SQL WHERE clause snippets for filtering trades before export - REMOVED ML-specific filters
  # Filters based on pattern labels will be handled implicitly by 'pattern_directions' in calculate_pnl.py
  filters: {}

# Settings for P&L calculation (calculate_pnl.py)
pnl_calculation_settings:
  # Duration in seconds for which a trade position is held after entry.
  # Default is 900 seconds (15 minutes).
  hold_time_seconds: 900